### ISSUE TITLE
Tricaster Presets

### ISSUE THREAD

**Issue by FabianEmele** [bitfocus/companion-module-newtek-tricaster#15]
Hi Companion Team, i am getting a Companion user and i like to knwo if there will be a Tricaster Set of Presets that will do more than Stream on/off Record on/of and take?
Tnak you so much fpr your answer.
Fabian

**Comment by bryce-seifert** [comment]
@FabianEmele The[ latest Companion beta build ](https://bitfocus.io/companion/download/builds/) has some new presets, namely for Media Player control. There are also presets for each source in preview/program.

If you have a particular action you'd like to see as a preset, just let me know. Otherwise there are quite a few to get started with at the moment.

**Comment by FabianEmele** [comment]
Hey Thank you very much.
Meanwhile I did change to vMIX but thank you for your help :)
Fabian
